### ISSUE TITLE
what is performance like on a 7bq4 text model?

### ISSUE THREAD

**Issue by Fuckingnameless** [c0zaut/RKLLM-Gradio#1]
and is memory footprint equivalent to a normal model?

**Comment by c0zaut** [comment]
I have an Orange Pi 5 Plus 32GB board, which has the RK3588 and can only do 8 bit. That being said - with w8a8 quantization, its about 50% the size on disk. Memory is a little trickier, since I need to do more experiments to calculate how the context window scales in memory. I think the RAM ratio is probably about the same as disk.
For q4, you would need a RK3576, which supports w4a16 quantization (equivalent to GGUF q4_0, according to the docs.)

Ref: https://github.com/airockchip/rknn-llm

**Comment by c0zaut** [comment]
Sorry - on my phone and accidentally hit close!
