### ISSUE TITLE
Gemma 9b and codergemma 7b giving no/gibberish/truncated responses

### ISSUE THREAD

**Issue by Siliconthaumaturgy** [c0zaut/RKLLM-Gradio#2]
First, thanks so much for putting this together.  I'm running on an OrangePi 5+ 16GB running Josh Riek Ubuntu.  NPU Driver 0.9.6 and runtime package 1.1.2.  

All models I've tried seem to work well in the interface except Gemma 2 9b and Codergemma 7b.  Gemma 2b seems to work inconsistently.  

However, when I run the models directly through the rkllm command, they respond appropriately, so I believe there is some issue in the GUI

Screenshot of rkllm function for Gemma 2 9b
![image](https://github.com/user-attachments/assets/5f2a55a8-22b9-4486-a326-d69bc6d2b51e)
****

Screenshot of command line for Gemma 2 9B in the gradio interface:
![image](https://github.com/user-attachments/assets/896e3f3d-d95e-4dd4-a813-c165e0744418)

**Comment by Siliconthaumaturgy** [comment]
I was able to solve this.  I noticed that another model I tried and failed referenced the "st_model_id" in the config file in the error messages.  I was using the runtime 1.1.2 version of Gemma 2 9b, when the config file referenced 1.1.1.  So, to resolve, I updated the config file line to "c01zaut/gemma-2-9b-it-rk3588-1.1.2"

**Comment by c0zaut** [comment]
Just committed the change! Thank you for pointing that out! 

For background, the st_model_id is the Huggingface repo that the tokenizer uses. I noticed that there were weird output results because of how the library interprets true newlines, so I changed the input type from prompt to token, and used the Transformers tokenizer to generate input.

Thank you so much for opening this issue, researching the fix, providing it, and marking the issue as closed!

I tested both of your prompts, and they were output correctly to stdout. Unfortunately, I still have a bit of work to do on the front end, since the gameboy did not render properly. I'm going to open a new issue for that.

![image](https://github.com/user-attachments/assets/e864a359-18be-4c3e-b892-eba844d64e94)

![image](https://github.com/user-attachments/assets/e5c35e90-28c5-4809-8776-ff50cc307ba4)
